name: Linter for active development branches

on:
  push:
    branches:
      - "**"
      - "!development"
      - "!production"

jobs:
  # Test with eslint and prettier
  linter-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install dependencies
        run: yarn run npm-run-all lint-check:*
